export {
  getAllPaquetes,
  getPaisesYCiudadesDistintos,
  buscarPaquetesPorPaisYCiudad,
  createPaquetesDetalles,
  createHotel,
  createPaquete,
  editarPaquete,
  type Hotel,
  type PaqueteEditarBody,
  type Paquete,
  type PaquetesDetalles,
  type PaquetesDetallesCreateInput,
  type HotelCreateInput,
  type PaqueteCreateInput,
  type PaisesYCiudadesDistintosResponse,
  type PaqueteResumen,
} from './paquetesService';
